### ISSUE TITLE
[Fix] 1차 릴리즈

### ISSUE THREAD

**Issue by Youngbae1126** [kw-bookmedicine/frontend#114]
### 📑 To-Do
- [x] 로그아웃 추가
- [x] 로그인 401 에러 해결

### 📑 To-Do
- [x] 이미지 없는 책의 경우, 로딩 썸네일 띄움
- [x] 화살표 클릭 시 페이지 라우팅 전부 연결되어 있는 지 확인

## 🗯️ 기타 사항
- [x] 로그인에 사용하는 유저 정보(kwadmin) DB에 있는 지 확인

**Comment by Youngbae1126** [comment]
로그아웃은 로직 구현은 되어 있는데, 쿠키가 안 담겨서 그런지 몰라도 에러 발생함.
원인 찾아보고 해결 필요
