### ISSUE TITLE
[ 🔥| hotfix ] 전시회 준비 전 점검

### ISSUE THREAD

**Issue by Youngbae1126** [kw-bookmedicine/frontend#353]
## 📑 To-Do
- [x] axios 파라미터 수정
- [x] 페이지 전환 에러 없는 지 확인
- [x] 중분류 맵핑 id값으로 변경
